name: Publish to Docker
on:
  push:
    branches:
      - main
      
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build container
        uses: docker/build-push-action@v1
        with:
          username: pandey-mithun
          password: ${{secrets.GITHUB_TOKEN}}
          registry: docker.pkg.github.com
          repository: pandey-mithun/publish-packages/games
          tag_with_sha: true
